# Generated by Django 6.0.1 on 2026-03-02 03:08

import apps.profiles.models.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.employee.employee_photo_path),
        ),
    ]
