# Generated by Django 6.0.1 on 2026-03-04 07:55

import apps.inventory.models.inventory
import apps.inventory.models.purchases
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_active_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='contacto principal'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='MX', verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, default='', max_length=13, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='nombre'),
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.inventory.models.inventory.item_photo_path, verbose_name='imagen')),
                ('caption', models.CharField(blank=True, default='', max_length=100, verbose_name='descripción')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Foto de producto',
                'verbose_name_plural': 'Fotos de producto',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.inventory.models.purchases.purchase_photo_path, verbose_name='imagen')),
                ('caption', models.CharField(blank=True, default='', max_length=100, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.purchase')),
            ],
            options={
                'verbose_name': 'Foto de compra',
                'verbose_name_plural': 'Fotos de compra',
                'ordering': ['created_at'],
            },
        ),
    ]
